"""Governed static website project generation for AEGIS agents."""
from __future__ import annotations

import html
import re
from pathlib import Path
from typing import Any

from .fabric import ActionContext, ActionError, _safe_path

_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")
_COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")
_MAX_TOTAL_BYTES = 5_000_000


def _required_text(args: dict[str, Any], key: str, limit: int) -> str:
    value = args.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ActionError(f"{key} is required")
    value = value.strip()
    if len(value) > limit:
        raise ActionError(f"{key} exceeds {limit} characters")
    return value


def _project_dir(context: ActionContext, args: dict[str, Any]) -> Path:
    raw = args.get("project_dir", args.get("name", "site"))
    if not isinstance(raw, str) or not raw.strip():
        raise ActionError("project_dir is required")
    raw = raw.strip()
    if "/" in raw or "\\" in raw or raw in {".", ".."}:
        raise ActionError("project_dir must be a single workspace-relative directory name")
    if not _NAME_RE.fullmatch(raw):
        raise ActionError("project_dir contains unsupported characters")
    return _safe_path(context.workspace, raw)


def _render(name: str, title: str, description: str, accent: str) -> dict[str, str]:
    safe_name = html.escape(name)
    safe_title = html.escape(title)
    safe_description = html.escape(description)
    return {
        "index.html": f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{safe_description}">
  <title>{safe_title}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="site-header"><a class="brand" href="#top">{safe_name}</a><nav aria-label="Primary"><a href="#features">Features</a><a href="#about">About</a></nav></header>
  <main id="top">
    <section class="hero"><p class="eyebrow">Generated by AEGIS</p><h1>{safe_title}</h1><p>{safe_description}</p><a class="button" href="#features">Explore</a></section>
    <section id="features" class="section"><h2>Built to move forward</h2><div class="grid"><article><h3>Fast</h3><p>A lightweight foundation with no external runtime dependencies.</p></article><article><h3>Accessible</h3><p>Semantic structure, responsive layout, and keyboard-friendly navigation.</p></article><article><h3>Auditable</h3><p>Every generated file is deterministic and contained inside the assigned workspace.</p></article></div></section>
    <section id="about" class="section"><h2>About this project</h2><p>{safe_description}</p></section>
  </main>
  <footer>Generated by AEGIS · <span id="year"></span></footer>
  <script src="script.js" defer></script>
</body>
</html>
''',
        "styles.css": f''':root {{ --accent: {accent}; --bg: #0b0d10; --panel: #13171c; --text: #f5f7fa; --muted: #aab2bd; }}
* {{ box-sizing: border-box; }} html {{ scroll-behavior: smooth; }} body {{ margin: 0; background: var(--bg); color: var(--text); font: 16px/1.6 system-ui, sans-serif; }}
a {{ color: inherit; text-decoration: none; }} .site-header {{ display:flex; justify-content:space-between; align-items:center; padding:24px 6vw; border-bottom:1px solid #252a31; }}
.brand {{ font-weight:800; letter-spacing:.04em; }} nav {{ display:flex; gap:24px; color:var(--muted); }} nav a:hover {{ color:var(--text); }}
.hero {{ min-height:68vh; display:grid; align-content:center; max-width:900px; margin:auto; padding:80px 6vw; }} .eyebrow {{ color:var(--accent); font-weight:700; text-transform:uppercase; letter-spacing:.14em; }}
h1 {{ font-size:clamp(3rem,9vw,7rem); line-height:.95; margin:12px 0 28px; max-width:850px; }} .hero p:not(.eyebrow) {{ color:var(--muted); font-size:1.2rem; max-width:680px; }}
.button {{ display:inline-block; width:max-content; margin-top:18px; padding:12px 20px; border-radius:10px; background:var(--accent); color:#050505; font-weight:800; }}
.section {{ max-width:1100px; margin:auto; padding:80px 6vw; }} .section h2 {{ font-size:2.2rem; }} .grid {{ display:grid; grid-template-columns:repeat(3,1fr); gap:20px; }} article {{ background:var(--panel); border:1px solid #252a31; border-radius:16px; padding:28px; }} article p, .section > p {{ color:var(--muted); }}
footer {{ padding:40px 6vw; border-top:1px solid #252a31; color:var(--muted); }}
@media (max-width:700px) {{ .site-header {{ padding:18px 5vw; }} nav {{ gap:12px; }} .hero {{ min-height:60vh; padding:60px 5vw; }} .section {{ padding:60px 5vw; }} .grid {{ grid-template-columns:1fr; }} }}
''',
        "script.js": "document.getElementById('year').textContent = new Date().getFullYear();\n",
        "README.md": f'''# {name}\n\nGenerated by the AEGIS Website Builder.\n\n## Project\n\n{title}\n\n{description}\n\n## Files\n\n- `index.html` — semantic page structure\n- `styles.css` — responsive styling\n- `script.js` — minimal local behavior\n\nThe generator does not execute commands, install packages, fetch remote assets, or write outside the assigned AEGIS workspace. Build, browser verification, and self-audit are separate governed stages.\n''',
    }


def website_create(context: ActionContext, args: dict[str, Any]) -> dict[str, Any]:
    """Create a deterministic static website inside the assigned workspace."""
    name = _required_text(args, "name", 64)
    if not _NAME_RE.fullmatch(name):
        raise ActionError("name contains unsupported characters")
    title = _required_text(args, "title", 120)
    description = _required_text(args, "description", 500)
    accent = args.get("accent", "#7dd3fc")
    if not isinstance(accent, str) or not _COLOR_RE.fullmatch(accent):
        raise ActionError("accent must be a six-digit hex color")

    project = _project_dir(context, {**args, "name": name})
    project_exists = project.exists()
    if project_exists and not project.is_dir():
        raise ActionError("project_dir exists and is not a directory")
    if project_exists and any(project.iterdir()) and args.get("overwrite") is not True:
        raise ActionError("project_dir is not empty; set overwrite=true to update generated files")

    files = _render(name, title, description, accent)
    total = sum(len(content.encode("utf-8")) for content in files.values())
    if total > _MAX_TOTAL_BYTES:
        raise ActionError("generated project exceeds action size limit")

    project.mkdir(parents=True, exist_ok=True)
    for relative, content in files.items():
        target = _safe_path(project, relative)
        target.write_text(content, encoding="utf-8")

    return {
        "project_dir": str(project.relative_to(context.workspace.resolve())),
        "files": sorted(files),
        "total_bytes": total,
        "overwrote": project_exists,
    }
